/**
 * WASM initialization for brepkit.
 *
 * Call `initBrepkit()` before using any brepkit functions.
 */

let initialized = false;

/**
 * Initialize the brepkit WASM module.
 *
 * This must be called once before using any brepkit functions.
 * Subsequent calls are no-ops.
 */
export async function initBrepkit(): Promise<void> {
  if (initialized) return;

  // The WASM module will be loaded from the pkg/ directory
  // generated by wasm-bindgen during the build step.
  // This is a placeholder until the WASM build pipeline is complete.

  initialized = true;
}

/**
 * Check whether the WASM module has been initialized.
 */
export function isInitialized(): boolean {
  return initialized;
}
